config/routes.rb
Rails.application.routes.draw do

  resources :elevators
  resources :columns
  resources :batteries
  resources :building_details
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :quotes
  resources :employees

  devise_for :users
  get 'quotes/new'
  get 'home/quote'
  get 'home/residential'
  get 'home/commercial'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role?
        can :manage, :all
        can :access, :rails_admin
        can :manage, :dashboard 
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :batteries
    has_many :building_details
    belongs_to :customer
    belongs_to :address
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :buildings
    has_one :user
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column
end

app/models/employee.rb


class Employee < ApplicationRecord
    belongs_to :user
end



app/models/lead.rb
class Lead < ApplicationRecord   
    has_one_attached :file
end



app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee
  belongs_to :customer, optional: true
 
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:building_type, :product_line, :apartments, :floors, :basements, :elevators, :companies, :parking_spots, :max_occupancy_per_floor, :corporations, :business_hours, :elevator_amount, :unit_price, :total_price, :install_fees, :final_price, :company_name, :email)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true, :method => "post") do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container pt-30 pb-30">
  <div class="row">	
		<div class="container pt-30 pb-30">
	

      <div class="col-sm-4 m-0">
        <%= form.label :building_type, class:"fs-16" %>
        <%= form.text_field :building_type, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :product_line, class:"fs-16"  %>
        <%= form.text_field :product_line, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :apartments, class:"fs-16"  %>
        <%= form.number_field :apartments, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :floors, class:"fs-16"  %>
        <%= form.number_field :floors, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :basements, class:"fs-16"  %>
        <%= form.number_field :basements, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :elevators, class:"fs-16"  %>
        <%= form.number_field :elevators, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :companies, class:"fs-16"  %>
        <%= form.number_field :companies, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :parking_spots, class:"fs-16"  %>
        <%= form.number_field :parking_spots, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :max_occupancy_per_floor, class:"fs-16"  %>
        <%= form.number_field :max_occupancy_per_floor, class:"form-control"  %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :corporations, class:"fs-16"  %>
        <%= form.number_field :corporations, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :business_hours, class:"fs-16"  %>
        <%= form.text_field :business_hours, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :elevator_amount, class:"fs-16"  %>
        <%= form.text_field :elevator_amount, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :unit_price, class:"fs-16"  %>
        <%= form.text_field :unit_price, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :total_price, class:"fs-16"  %>
        <%= form.text_field :total_price, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :install_fees, class:"fs-16"  %>
        <%= form.text_field :install_fees, class:"form-control" %>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :final_price, class:"fs-16"  %>
        <%= form.text_field :final_price, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :company_name, class:"fs-16"  %>
        <%= form.text_field :company_name, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.label :email, class:"fs-16"  %>
        <%= form.text_field :email, class:"form-control"%>
      </div>

      <div class="col-sm-4 m-0">
        <%= form.submit %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Building type</th>
      <th>Product line</th>
      <th>Apartments</th>
      <th>Floors</th>
      <th>Basements</th>
      <th>Elevators</th>
      <th>Companies</th>
      <th>Parking spots</th>
      <th>Max occupancy per floor</th>
      <th>Corporations</th>
      <th>Business hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.building_type %></td>
        <td><%= quote.product_line %></td>
        <td><%= quote.apartments %></td>
        <td><%= quote.floors %></td>
        <td><%= quote.basements %></td>
        <td><%= quote.elevators %></td>
        <td><%= quote.companies %></td>
        <td><%= quote.parking_spots %></td>
        <td><%= quote.max_occupancy_per_floor %></td>
        <td><%= quote.corporations %></td>
        <td><%= quote.business_hours %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>Cofigure elevator setup</h1>
			<div class="container pt-30 pb-30">
                 
				<div class="row">

					<div class="col-md-6">
				
					<form action="" id="quoteForm_">
						<div>
							<select onchange="getBuildingType()" id="building-type">
								<option value="" disabled selected>Select Building Type</option>
								<option id="residential" value="residential1">Residential</option>
								<option id="commercial" value="commercial1">Commercial</option>
								<option id="corporate" value="corporate1">Corporate</option>
								<option id="hybrid" value="hybrid1">Hybrid</option>
							</select>
						</div>

						<div class="fs-grid">
							<div id="residential1" class="building_type">
								<div id=resultsInputsID_dropdown_residential >
									<label class="fs-16">Product Line *</label>
									<select onchange="getInstallationFees(),getElevatorTotalPrice(),getElevatorUnitPrice(),getFinalPrice()"  id="resultsInputsIDResidential" class="form-control">
										<option value="" disabled selected>Select Product Line</option>
										<option value="standard">Standard</option>
										<option value="premium">Premium</option>
										<option value="excelium">Excelium</option>
										
									</select>
								</div>
								<div id="number-of-apartments" class="col-sm-8 m-0">
									<label class="fs-16">N. of Apartments *</label>
									<input oninput="getElevatorAmount(),getElevatorTotalPrice(),getInstallationFees(),getFinalPrice()" id="numberOfApartmentsResidential" type="text" class="form-control" value="">
								</div>
								<div id="number-of-floors" class="col-sm-8 m-0">
									<label class="fs-16">N. of Floors *</label>
									<input oninput="getElevatorAmount(),getElevatorTotalPrice(),getInstallationFees(),getFinalPrice()" id="numberOfFloorsResidential" type="text" class="form-control" value="">
								</div>
								
								<div id="number-of-basements" class="col-sm-8 m-0">
									<label class="fs-16">N. of Basements</label>
									<input id="numberOfBasementsResidential" type="text" class="form-control" value="">
								</div>
							</div>
							<div id="commercial1" class="building_type">
								<div id=resultsInputsID_dropdown_commercial >
									<label class="fs-16">Product Line *</label>
									<select onchange="getCommercialElevatorUnitPrice(),getElevatorTotalPriceCom(),getInstallationFeesCom(),getFinalPriceCom()" id="resultsInputsIDCommercial" class="form-control">
										<option value="" disabled selected>Select Product Line</option>
										<option value="standard">Standard</option>
										<option value="premium">Premium</option>
										<option value="excelium">Excelium</option>
									</select>
								</div>
								<div id="number-of-elevators" class="col-sm-8 m-0">
									<label class="fs-16">N. of Elevators *</label>
									<input oninput="getElevatorTotalPriceCom(),getElevatorAmountCom2(),getInstallationFeesCom(),getFinalPriceCom()" id="numberOfElevatorsCommercial" type="text" class="form-control" value="">
								</div>
								<div id="number-of-floors" class="col-sm-8 m-0">
									<label class="fs-16">N. of Floors</label>
									<input id="numberOfFloorsCommercial" type="text" class="form-control" value="">
								</div>
								
								<div id="number-of-basements" class="col-sm-8 m-0">
									<label class="fs-16">N. of Basements</label>
									<input id="numberOfBasementsCommercial" type="text" class="form-control" value="">
								</div>
								<div id="number-of-companies" class="col-sm-8 m-0">
									<label class="fs-16">N. of Companies</label>
									<input id="numberOfCompaniesCommercial" type="text" class="form-control" value="">
								</div>
								<div id="number-of-parking-spots" class="col-sm-8 m-0">
									<label class="fs-16">N. of Parking Spots</label>
									<input id="numberOfParkingSpotsCommercial" type="text" class="form-control" value="">
								</div>
							</div>
							<div id="corporate1" class="building_type">
								<div id=resultsInputsID_dropdown_corporate >
									<label class="fs-16">Product Line *</label>
									<select onchange="getCorporateElevatorUnitPrice(),getElevatorTotalPriceCorp(),getInstallationFeesCorp(),getFinalPriceCorp()" id="resultsInputsIDCorporate" class="form-control">
										<option value="" disabled selected>Select Product Line</option>
										<option value="standard">Standard</option>
										<option value="premium">Premium</option>
										<option value="excelium">Excelium</option>
										
									</select>
								</div>
								<div id="number-of-floors" class="col-sm-8 m-0">
									<label class="fs-16">N. of Floors *</label>
									<input oninput="getElevatorAmountCorp(),getElevatorTotalPriceCorp(),getInstallationFeesCorp(),getFinalPriceCorp()" id="numberOfFloorsCorporate" type="text" class="form-control" value="">
								</div>
								<div id="number-of-basements" oninput="getElevatorAmountCorp(),getElevatorTotalPriceCorp(),getInstallationFeesCorp(),getFinalPriceCorp()" class="col-sm-8 m-0">
									<label class="fs-16">N. of Basements *</label>
									<input id="numberOfBasementsCorporate" type="text" class="form-control" value="">
								</div>
								<div id="maximum-occupancy" class="col-sm-8 m-0">
									<label class="fs-16">Maximum Occupancy per Floor *</label>
									<input oninput="getElevatorAmountCorp(),getElevatorTotalPriceCorp(),getInstallationFeesCorp(),getFinalPriceCorp()" id="maximumOccupancyCorporate" type="text" class="form-control" value="">
								</div>
								<div id="number-of-parking-spots" class="col-sm-8 m-0">
									<label class="fs-16">N. of Parking Spots</label>
									<input id="numberOfParkingSpotsCorporate" type="text" class="form-control" value="">
								</div>
								<div id="number-of-corporations" class="col-sm-8 m-0">
									<label class="fs-16">N. of Corporations</label>
									<input id="numberOfCorporationsCorporate" type="text" class="form-control" value="">
								</div>
								
							</div>
							<div id="hybrid1" class="building_type">
								<div id=resultsInputsID_dropdown_hybrid>
									<label class="fs-16">Product Line *</label>
									<select onchange="getFinalPriceHybrid(),getInstallationFeesHybrid(),getElevatorTotalPriceHybrid(),getElevatorAmountHybrid(),getHybridElevatorUnitPrice()" id="resultsInputsIDHybrid" class="form-control">
										<option value="" disabled selected>Select Product Line</option>
										<option value="standard">Standard</option>
										<option value="premium">Premium</option>
										<option value="excelium">Excelium</option>
									</select>
								</div>
								<div id="number-of-floors" class="col-sm-8 m-0">
									<label class="fs-16">N. of Floors *</label>
									<input oninput="getFinalPriceHybrid(),getInstallationFeesHybrid(),getElevatorTotalPriceHybrid(),getElevatorAmountHybrid()" id="numberOfFloorsHybrid" type="text" class="form-control" value="">
								</div>
								<div id="number-of-basements" class="col-sm-8 m-0">
									<label class="fs-16">N. of Basements *</label>
									<input oninput="getFinalPriceHybrid(),getInstallationFeesHybrid(),getElevatorTotalPriceHybrid(),getElevatorAmountHybrid()" id="numberOfBasementsHybrid" type="text" class="form-control" value="">
								</div>
								<div id="maximum-occupancy" class="col-sm-8 m-0">
									<label class="fs-16">Maximum Occupancy per Floor *</label>
									<input oninput="getFinalPriceHybrid(),getInstallationFeesHybrid(),getElevatorTotalPriceHybrid(),getElevatorAmountHybrid()" id="maximumOccupancyHybrid" type="text" class="form-control" value="">
								</div>
								<div id="number-of-companies" class="col-sm-8 m-0">
									<label class="fs-16">N. of Companies</label>
									<input id="numberOfCompaniesHybrid" type="text" class="form-control" value="">
								</div>
								<div id="number-of-parking-spots" class="col-sm-8 m-0">
									<label class="fs-16">N. of Parking Spots</label>
									<input id="numberOfParkingSpotsHybrid" type="text" class="form-control" value="">
								</div>
								<div id="business-hours" class="col-sm-8 m-0">
									<label class="fs-16">Business Hours</label>
									<input id="businessHoursHybrid" type="text" class="form-control" value="">
								</div>
							</div>
						</div>
					</form>
						

					</div>

					<div class="col-md-6 mb-30">


						<table class="table fs-14 m-0">
							<tbody>
								<tr>
									<div id="elevator-amount">
									<td class="b-0 p-3">Elevator Amount</td>
									<td class="b-0 p-3 text-right text-danger fw-800"><span id="result-ElevatorAmount">0</span></td>
								</div>
								</tr>
								<tr>
									<div id="elevator-unit-price">
									<td class="b-0 p-3">Elevator Unit Price</td>
									<td class="b-0 p-3 text-right text-danger fw-800">$<span id="result-ElevatorUnit">0.00</span></td>
								</div>
								</tr>
								<tr>
									<div id="elevator-total-price">
									<td class="b-0 p-3">Elevator Total Price</td>
									<td class="b-0 p-3 text-right text-danger fw-800">$<span id="result-ElevatorPrice">0.00</span></td>
								</div>
								</tr>
								<tr>
									<div id="installation-fees"> 
									<td class="b-0 p-3">Installation Fees</td>
									<td class="b-0 p-3 text-right text-danger fw-800">$<span id="result-ElevatorFees">0.00</span></td>
								</div>
								</tr>
							</tbody>
						</table>

						<hr />

						<table class="table fs-14 m-0">
							<tbody>
								<tr>
									<div id="final-price">
									<td class="b-0 p-3">Final Price</td>
									<td class="b-0 p-3 text-right text-black fw-800">$<span id="result-FinalPrice">0.00</span></td>
								</div>
								</tr>
								
							</tbody>
						</table>


					</div>

				</div>
				
<h1>Recieve discount on installation if you fill in the fields below manually!</h1>
  <%= render 'form', quote: @quote %>
  
<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building type:</strong>
  <%= @quote.building_type %>
</p>

<p>
  <strong>Product line:</strong>
  <%= @quote.product_line %>
</p>

<p>
  <strong>Apartments:</strong>
  <%= @quote.apartments %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @quote.floors %>
</p>

<p>
  <strong>Basements:</strong>
  <%= @quote.basements %>
</p>

<p>
  <strong>Elevators:</strong>
  <%= @quote.elevators %>
</p>

<p>
  <strong>Companies:</strong>
  <%= @quote.companies %>
</p>

<p>
  <strong>Parking spots:</strong>
  <%= @quote.parking_spots %>
</p>

<p>
  <strong>Max occupancy per floor:</strong>
  <%= @quote.max_occupancy_per_floor %>
</p>

<p>
  <strong>Corporations:</strong>
  <%= @quote.corporations %>
</p>

<p>
  <strong>Business hours:</strong>
  <%= @quote.business_hours %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>