config/routes.rb
Rails.application.routes.draw do

  resources :elevators
  resources :columns
  resources :batteries
  resources :building_details
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :quotes
  resources :employees

  devise_for :users
  get 'quotes/new'
  get 'home/quote'
  get 'home/residential'
  get 'home/commercial'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role?
        can :manage, :all
        can :access, :rails_admin
        can :manage, :dashboard 
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :batteries
    has_many :building_details
    belongs_to :customer
    belongs_to :address
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :buildings
    has_one :user
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column
end

app/models/employee.rb


class Employee < ApplicationRecord
    belongs_to :user
end



app/models/lead.rb
class Lead < ApplicationRecord   
    has_one_attached :file
end



app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee
  belongs_to :customer, optional: true
 
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :set_elevator, only: %i[ show edit update destroy ]

  # GET /elevators or /elevators.json
  def index
    @elevators = Elevator.all
  end

  # GET /elevators/1 or /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = Elevator.new
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators or /elevators.json
  def create
    @elevator = Elevator.new(elevator_params)

    respond_to do |format|
      if @elevator.save
        format.html { redirect_to @elevator, notice: "Elevator was successfully created." }
        format.json { render :show, status: :created, location: @elevator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1 or /elevators/1.json
  def update
    respond_to do |format|
      if @elevator.update(elevator_params)
        format.html { redirect_to @elevator, notice: "Elevator was successfully updated." }
        format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1 or /elevators/1.json
  def destroy
    @elevator.destroy
    respond_to do |format|
      format.html { redirect_to elevators_url, notice: "Elevator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = Elevator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elevator_params
      params.require(:elevator).permit(:column_id, :serial_number, :model, :type, :status, :date_of_commissioning, :last_inspection, :certificate_of_inspection, :information, :notes)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.number_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :date_of_commissioning %>
    <%= form.date_select :date_of_commissioning %>
  </div>

  <div class="field">
    <%= form.label :last_inspection %>
    <%= form.date_select :last_inspection %>
  </div>

  <div class="field">
    <%= form.label :certificate_of_inspection %>
    <%= form.text_field :certificate_of_inspection %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elevators/edit.html.erb
<h1>Editing Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Show', @elevator %> |
<%= link_to 'Back', elevators_path %>

app/views/elevators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elevators</h1>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Serial number</th>
      <th>Model</th>
      <th>Type</th>
      <th>Status</th>
      <th>Date of commissioning</th>
      <th>Last inspection</th>
      <th>Certificate of inspection</th>
      <th>Information</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <tr>
        <td><%= elevator.column_id %></td>
        <td><%= elevator.serial_number %></td>
        <td><%= elevator.model %></td>
        <td><%= elevator.type %></td>
        <td><%= elevator.status %></td>
        <td><%= elevator.date_of_commissioning %></td>
        <td><%= elevator.last_inspection %></td>
        <td><%= elevator.certificate_of_inspection %></td>
        <td><%= elevator.information %></td>
        <td><%= elevator.notes %></td>
        <td><%= link_to 'Show', elevator %></td>
        <td><%= link_to 'Edit', edit_elevator_path(elevator) %></td>
        <td><%= link_to 'Destroy', elevator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elevator', new_elevator_path %>

app/views/elevators/new.html.erb
<h1>New Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Column:</strong>
  <%= @elevator.column_id %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @elevator.serial_number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @elevator.model %>
</p>

<p>
  <strong>Elevator type:</strong>
  <%= @elevator.elevator_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @elevator.status %>
</p>

<p>
  <strong>Date of commissioning:</strong>
  <%= @elevator.date_of_commissioning %>
</p>

<p>
  <strong>Last inspection:</strong>
  <%= @elevator.last_inspection %>
</p>

<p>
  <strong>Certificate of inspection:</strong>
  <%= @elevator.certificate_of_inspection %>
</p>

<p>
  <strong>Information:</strong>
  <%= @elevator.information %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @elevator.notes %>
</p>

<%= link_to 'Edit', edit_elevator_path(@elevator) %> |
<%= link_to 'Back', elevators_path %>