config/routes.rb
Rails.application.routes.draw do

  resources :elevators
  resources :columns
  resources :batteries
  resources :building_details
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :quotes
  resources :employees

  devise_for :users
  get 'quotes/new'
  get 'home/quote'
  get 'home/residential'
  get 'home/commercial'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role?
        can :manage, :all
        can :access, :rails_admin
        can :manage, :dashboard 
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :batteries
    has_many :building_details
    belongs_to :customer
    belongs_to :address
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :buildings
    has_one :user
end

app/models/elevator.rb
class Elevator < ApplicationRecord
    belongs_to :column
end

app/models/employee.rb


class Employee < ApplicationRecord
    belongs_to :user
end



app/models/lead.rb
class Lead < ApplicationRecord   
    has_one_attached :file
end



app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee
  belongs_to :customer, optional: true
 
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: %i[ show edit update destroy ]

  # GET /columns or /columns.json
  def index
    @columns = Column.all
  end

  # GET /columns/1 or /columns/1.json
  def show
  end

  # GET /columns/new
  def new
    @column = Column.new
  end

  # GET /columns/1/edit
  def edit
  end

  # POST /columns or /columns.json
  def create
    @column = Column.new(column_params)

    respond_to do |format|
      if @column.save
        format.html { redirect_to @column, notice: "Column was successfully created." }
        format.json { render :show, status: :created, location: @column }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /columns/1 or /columns/1.json
  def update
    respond_to do |format|
      if @column.update(column_params)
        format.html { redirect_to @column, notice: "Column was successfully updated." }
        format.json { render :show, status: :ok, location: @column }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1 or /columns/1.json
  def destroy
    @column.destroy
    respond_to do |format|
      format.html { redirect_to columns_url, notice: "Column was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_column
      @column = Column.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def column_params
      params.require(:column).permit(:battery_id, :type, :num_floors_served, :status, :information, :notes)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/columns/_form.html.erb
<%= form_with(model: column, local: true) do |form| %>
  <% if column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
      <% column.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :battery_id %>
    <%= form.number_field :battery_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :num_floors_served %>
    <%= form.number_field :num_floors_served %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing Column</h1>

<%= render 'form', column: @column %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Columns</h1>

<table>
  <thead>
    <tr>
      <th>Battery</th>
      <th>Type</th>
      <th>Num floors served</th>
      <th>Status</th>
      <th>Information</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @columns.each do |column| %>
      <tr>
        <td><%= column.battery_id %></td>
        <td><%= column.type %></td>
        <td><%= column.num_floors_served %></td>
        <td><%= column.status %></td>
        <td><%= column.information %></td>
        <td><%= column.notes %></td>
        <td><%= link_to 'Show', column %></td>
        <td><%= link_to 'Edit', edit_column_path(column) %></td>
        <td><%= link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Column', new_column_path %>

app/views/columns/new.html.erb
<h1>New Column</h1>

<%= render 'form', column: @column %>

<%= link_to 'Back', columns_path %>

app/views/columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Battery:</strong>
  <%= @column.battery_id %>
</p>

<p>
  <strong>column Type:</strong>
  <%= @column.column_type %>
</p>

<p>
  <strong>Num floors served:</strong>
  <%= @column.num_floors_served %>
</p>

<p>
  <strong>Status:</strong>
  <%= @column.status %>
</p>

<p>
  <strong>Information:</strong>
  <%= @column.information %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @column.notes %>
</p>

<%= link_to 'Edit', edit_column_path(@column) %> |
<%= link_to 'Back', columns_path %>